"""Añadir campos normalizados a Organo

Revision ID: 4cbb65bd3b8d
Revises: 4fed545c8afd
Create Date: 2025-06-23 15:44:57.921756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbb65bd3b8d'
down_revision: Union[str, None] = '4fed545c8afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organo_nivel1_nivel2_nivel3'), table_name='organo')
    op.create_index('ix_organo_nivel1_nivel2_nivel3', 'organo', ['nivel1_norm', 'nivel2_norm', 'nivel3_norm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organo_nivel1_nivel2_nivel3', table_name='organo')
    op.create_index(op.f('ix_organo_nivel1_nivel2_nivel3'), 'organo', ['nivel1', 'nivel2', 'nivel3'], unique=False)
    # ### end Alembic commands ###
