"""Añadir campos normalizados a Organo

Revision ID: 4fed545c8afd
Revises: d2611d6eb6f5
Create Date: 2025-06-23 15:41:58.957117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fed545c8afd'
down_revision: Union[str, None] = 'd2611d6eb6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organo', sa.Column('nivel1_norm', sa.String(), nullable=True))
    op.add_column('organo', sa.Column('nivel2_norm', sa.String(), nullable=True))
    op.add_column('organo', sa.Column('nivel3_norm', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organo', 'nivel3_norm')
    op.drop_column('organo', 'nivel2_norm')
    op.drop_column('organo', 'nivel1_norm')
    # ### end Alembic commands ###
